// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: aviator/aviator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRoundRequest) Reset() {
	*x = GetCurrentRoundRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRoundRequest) ProtoMessage() {}

func (x *GetCurrentRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRoundRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRoundRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{0}
}

type StartRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoundRequest) Reset() {
	*x = StartRoundRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoundRequest) ProtoMessage() {}

func (x *StartRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoundRequest.ProtoReflect.Descriptor instead.
func (*StartRoundRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{1}
}

type StreamRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRoundRequest) Reset() {
	*x = StreamRoundRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRoundRequest) ProtoMessage() {}

func (x *StreamRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRoundRequest.ProtoReflect.Descriptor instead.
func (*StreamRoundRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{2}
}

type GetRoundByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundByIdRequest) Reset() {
	*x = GetRoundByIdRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundByIdRequest) ProtoMessage() {}

func (x *GetRoundByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRoundByIdRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoundByIdRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GetRoundHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundHistoryRequest) Reset() {
	*x = GetRoundHistoryRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundHistoryRequest) ProtoMessage() {}

func (x *GetRoundHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRoundHistoryRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoundHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBetsByRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetsByRoundRequest) Reset() {
	*x = GetBetsByRoundRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetsByRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetsByRoundRequest) ProtoMessage() {}

func (x *GetBetsByRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetsByRoundRequest.ProtoReflect.Descriptor instead.
func (*GetBetsByRoundRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{5}
}

func (x *GetBetsByRoundRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GetMyActiveBetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyActiveBetsRequest) Reset() {
	*x = GetMyActiveBetsRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyActiveBetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyActiveBetsRequest) ProtoMessage() {}

func (x *GetMyActiveBetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyActiveBetsRequest.ProtoReflect.Descriptor instead.
func (*GetMyActiveBetsRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyActiveBetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPlayerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatsRequest) Reset() {
	*x = GetPlayerStatsRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsRequest) ProtoMessage() {}

func (x *GetPlayerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayerStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PlaceBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{8}
}

func (x *PlaceBetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceBetRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type CancelBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BetId         string                 `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBetRequest) Reset() {
	*x = CancelBetRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBetRequest) ProtoMessage() {}

func (x *CancelBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBetRequest.ProtoReflect.Descriptor instead.
func (*CancelBetRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{9}
}

func (x *CancelBetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelBetRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

type CashOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BetId         string                 `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashOutRequest) Reset() {
	*x = CashOutRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutRequest) ProtoMessage() {}

func (x *CashOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutRequest.ProtoReflect.Descriptor instead.
func (*CashOutRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{10}
}

func (x *CashOutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CashOutRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

type SetAutoCashOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BetId         string                 `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoCashOutRequest) Reset() {
	*x = SetAutoCashOutRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoCashOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoCashOutRequest) ProtoMessage() {}

func (x *SetAutoCashOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoCashOutRequest.ProtoReflect.Descriptor instead.
func (*SetAutoCashOutRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{11}
}

func (x *SetAutoCashOutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetAutoCashOutRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *SetAutoCashOutRequest) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type ClearAutoCashOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BetId         string                 `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAutoCashOutRequest) Reset() {
	*x = ClearAutoCashOutRequest{}
	mi := &file_aviator_aviator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAutoCashOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAutoCashOutRequest) ProtoMessage() {}

func (x *ClearAutoCashOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAutoCashOutRequest.ProtoReflect.Descriptor instead.
func (*ClearAutoCashOutRequest) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{12}
}

func (x *ClearAutoCashOutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearAutoCashOutRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

type RoundResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoundId           string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,3,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	CrashMultiplier   float64                `protobuf:"fixed64,4,opt,name=crash_multiplier,json=crashMultiplier,proto3" json:"crash_multiplier,omitempty"`
	StartedAt         int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CrashedAt         int64                  `protobuf:"varint,6,opt,name=crashed_at,json=crashedAt,proto3" json:"crashed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoundResponse) Reset() {
	*x = RoundResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResponse) ProtoMessage() {}

func (x *RoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResponse.ProtoReflect.Descriptor instead.
func (*RoundResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{13}
}

func (x *RoundResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RoundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoundResponse) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *RoundResponse) GetCrashMultiplier() float64 {
	if x != nil {
		return x.CrashMultiplier
	}
	return 0
}

func (x *RoundResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RoundResponse) GetCrashedAt() int64 {
	if x != nil {
		return x.CrashedAt
	}
	return 0
}

type RoundTick struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoundId           string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,3,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	ServerTime        int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoundTick) Reset() {
	*x = RoundTick{}
	mi := &file_aviator_aviator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundTick) ProtoMessage() {}

func (x *RoundTick) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundTick.ProtoReflect.Descriptor instead.
func (*RoundTick) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{14}
}

func (x *RoundTick) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RoundTick) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoundTick) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *RoundTick) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type BetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         string                 `protobuf:"bytes,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	RoundId       string                 `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,6,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetResponse) Reset() {
	*x = BetResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResponse) ProtoMessage() {}

func (x *BetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResponse.ProtoReflect.Descriptor instead.
func (*BetResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{15}
}

func (x *BetResponse) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BetResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BetResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BetResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

type CashOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         string                 `protobuf:"bytes,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	PayoutCents   int64                  `protobuf:"varint,3,opt,name=payout_cents,json=payoutCents,proto3" json:"payout_cents,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,4,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashOutResponse) Reset() {
	*x = CashOutResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutResponse) ProtoMessage() {}

func (x *CashOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutResponse.ProtoReflect.Descriptor instead.
func (*CashOutResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{16}
}

func (x *CashOutResponse) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *CashOutResponse) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *CashOutResponse) GetPayoutCents() int64 {
	if x != nil {
		return x.PayoutCents
	}
	return 0
}

func (x *CashOutResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

type AutoCashOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         string                 `protobuf:"bytes,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoCashOutResponse) Reset() {
	*x = AutoCashOutResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoCashOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCashOutResponse) ProtoMessage() {}

func (x *AutoCashOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCashOutResponse.ProtoReflect.Descriptor instead.
func (*AutoCashOutResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{17}
}

func (x *AutoCashOutResponse) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *AutoCashOutResponse) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *AutoCashOutResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type BetEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BetId             string                 `protobuf:"bytes,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents       int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CashoutMultiplier float64                `protobuf:"fixed64,5,opt,name=cashout_multiplier,json=cashoutMultiplier,proto3" json:"cashout_multiplier,omitempty"`
	PayoutCents       int64                  `protobuf:"varint,6,opt,name=payout_cents,json=payoutCents,proto3" json:"payout_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BetEntry) Reset() {
	*x = BetEntry{}
	mi := &file_aviator_aviator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetEntry) ProtoMessage() {}

func (x *BetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetEntry.ProtoReflect.Descriptor instead.
func (*BetEntry) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{18}
}

func (x *BetEntry) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *BetEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BetEntry) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BetEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BetEntry) GetCashoutMultiplier() float64 {
	if x != nil {
		return x.CashoutMultiplier
	}
	return 0
}

func (x *BetEntry) GetPayoutCents() int64 {
	if x != nil {
		return x.PayoutCents
	}
	return 0
}

type BetsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bets          []*BetEntry            `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetsListResponse) Reset() {
	*x = BetsListResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetsListResponse) ProtoMessage() {}

func (x *BetsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetsListResponse.ProtoReflect.Descriptor instead.
func (*BetsListResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{19}
}

func (x *BetsListResponse) GetBets() []*BetEntry {
	if x != nil {
		return x.Bets
	}
	return nil
}

type RoundHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        []*RoundResponse       `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundHistoryResponse) Reset() {
	*x = RoundHistoryResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundHistoryResponse) ProtoMessage() {}

func (x *RoundHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundHistoryResponse.ProtoReflect.Descriptor instead.
func (*RoundHistoryResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{20}
}

func (x *RoundHistoryResponse) GetRounds() []*RoundResponse {
	if x != nil {
		return x.Rounds
	}
	return nil
}

type PlayerStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalBets         int32                  `protobuf:"varint,1,opt,name=total_bets,json=totalBets,proto3" json:"total_bets,omitempty"`
	TotalWins         int32                  `protobuf:"varint,2,opt,name=total_wins,json=totalWins,proto3" json:"total_wins,omitempty"`
	TotalWageredCents int64                  `protobuf:"varint,3,opt,name=total_wagered_cents,json=totalWageredCents,proto3" json:"total_wagered_cents,omitempty"`
	TotalWonCents     int64                  `protobuf:"varint,4,opt,name=total_won_cents,json=totalWonCents,proto3" json:"total_won_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerStatsResponse) Reset() {
	*x = PlayerStatsResponse{}
	mi := &file_aviator_aviator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsResponse) ProtoMessage() {}

func (x *PlayerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aviator_aviator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsResponse.ProtoReflect.Descriptor instead.
func (*PlayerStatsResponse) Descriptor() ([]byte, []int) {
	return file_aviator_aviator_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerStatsResponse) GetTotalBets() int32 {
	if x != nil {
		return x.TotalBets
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWins() int32 {
	if x != nil {
		return x.TotalWins
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWageredCents() int64 {
	if x != nil {
		return x.TotalWageredCents
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWonCents() int64 {
	if x != nil {
		return x.TotalWonCents
	}
	return 0
}

var File_aviator_aviator_proto protoreflect.FileDescriptor

const file_aviator_aviator_proto_rawDesc = "" +
	"\n" +
	"\x15aviator/aviator.proto\x12\aaviator\"\x18\n" +
	"\x16GetCurrentRoundRequest\"\x13\n" +
	"\x11StartRoundRequest\"\x14\n" +
	"\x12StreamRoundRequest\"0\n" +
	"\x13GetRoundByIdRequest\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\".\n" +
	"\x16GetRoundHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"2\n" +
	"\x15GetBetsByRoundRequest\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\"1\n" +
	"\x16GetMyActiveBetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x15GetPlayerStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x0fPlaceBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\"B\n" +
	"\x10CancelBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06bet_id\x18\x02 \x01(\tR\x05betId\"@\n" +
	"\x0eCashOutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06bet_id\x18\x02 \x01(\tR\x05betId\"g\n" +
	"\x15SetAutoCashOutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06bet_id\x18\x02 \x01(\tR\x05betId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\"I\n" +
	"\x17ClearAutoCashOutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06bet_id\x18\x02 \x01(\tR\x05betId\"\xda\x01\n" +
	"\rRoundResponse\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12current_multiplier\x18\x03 \x01(\x01R\x11currentMultiplier\x12)\n" +
	"\x10crash_multiplier\x18\x04 \x01(\x01R\x0fcrashMultiplier\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"crashed_at\x18\x06 \x01(\x03R\tcrashedAt\"\x8e\x01\n" +
	"\tRoundTick\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12current_multiplier\x18\x03 \x01(\x01R\x11currentMultiplier\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"\xb8\x01\n" +
	"\vBetResponse\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\tR\x05betId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\tR\aroundId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rbalance_cents\x18\x06 \x01(\x03R\fbalanceCents\"\x90\x01\n" +
	"\x0fCashOutResponse\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\tR\x05betId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x01R\n" +
	"multiplier\x12!\n" +
	"\fpayout_cents\x18\x03 \x01(\x03R\vpayoutCents\x12#\n" +
	"\rbalance_cents\x18\x04 \x01(\x03R\fbalanceCents\"d\n" +
	"\x13AutoCashOutResponse\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\tR\x05betId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x01R\n" +
	"multiplier\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\xc7\x01\n" +
	"\bBetEntry\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\tR\x05betId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12-\n" +
	"\x12cashout_multiplier\x18\x05 \x01(\x01R\x11cashoutMultiplier\x12!\n" +
	"\fpayout_cents\x18\x06 \x01(\x03R\vpayoutCents\"9\n" +
	"\x10BetsListResponse\x12%\n" +
	"\x04bets\x18\x01 \x03(\v2\x11.aviator.BetEntryR\x04bets\"F\n" +
	"\x14RoundHistoryResponse\x12.\n" +
	"\x06rounds\x18\x01 \x03(\v2\x16.aviator.RoundResponseR\x06rounds\"\xab\x01\n" +
	"\x13PlayerStatsResponse\x12\x1d\n" +
	"\n" +
	"total_bets\x18\x01 \x01(\x05R\ttotalBets\x12\x1d\n" +
	"\n" +
	"total_wins\x18\x02 \x01(\x05R\ttotalWins\x12.\n" +
	"\x13total_wagered_cents\x18\x03 \x01(\x03R\x11totalWageredCents\x12&\n" +
	"\x0ftotal_won_cents\x18\x04 \x01(\x03R\rtotalWonCents2\xc8\a\n" +
	"\x0eAviatorService\x12J\n" +
	"\x0fGetCurrentRound\x12\x1f.aviator.GetCurrentRoundRequest\x1a\x16.aviator.RoundResponse\x12:\n" +
	"\bPlaceBet\x12\x18.aviator.PlaceBetRequest\x1a\x14.aviator.BetResponse\x12<\n" +
	"\tCancelBet\x12\x19.aviator.CancelBetRequest\x1a\x14.aviator.BetResponse\x12<\n" +
	"\aCashOut\x12\x17.aviator.CashOutRequest\x1a\x18.aviator.CashOutResponse\x12N\n" +
	"\x0eSetAutoCashOut\x12\x1e.aviator.SetAutoCashOutRequest\x1a\x1c.aviator.AutoCashOutResponse\x12R\n" +
	"\x10ClearAutoCashOut\x12 .aviator.ClearAutoCashOutRequest\x1a\x1c.aviator.AutoCashOutResponse\x12M\n" +
	"\x0fGetMyActiveBets\x12\x1f.aviator.GetMyActiveBetsRequest\x1a\x19.aviator.BetsListResponse\x12Q\n" +
	"\x0fGetRoundHistory\x12\x1f.aviator.GetRoundHistoryRequest\x1a\x1d.aviator.RoundHistoryResponse\x12D\n" +
	"\fGetRoundById\x12\x1c.aviator.GetRoundByIdRequest\x1a\x16.aviator.RoundResponse\x12K\n" +
	"\x0eGetBetsByRound\x12\x1e.aviator.GetBetsByRoundRequest\x1a\x19.aviator.BetsListResponse\x12N\n" +
	"\x0eGetPlayerStats\x12\x1e.aviator.GetPlayerStatsRequest\x1a\x1c.aviator.PlayerStatsResponse\x12@\n" +
	"\n" +
	"StartRound\x12\x1a.aviator.StartRoundRequest\x1a\x16.aviator.RoundResponse\x12G\n" +
	"\x12StreamRoundUpdates\x12\x1b.aviator.StreamRoundRequest\x1a\x12.aviator.RoundTick0\x01B3Z1github.com/akadilxbet/aviator-service/internal/pbb\x06proto3"

var (
	file_aviator_aviator_proto_rawDescOnce sync.Once
	file_aviator_aviator_proto_rawDescData []byte
)

func file_aviator_aviator_proto_rawDescGZIP() []byte {
	file_aviator_aviator_proto_rawDescOnce.Do(func() {
		file_aviator_aviator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aviator_aviator_proto_rawDesc), len(file_aviator_aviator_proto_rawDesc)))
	})
	return file_aviator_aviator_proto_rawDescData
}

var file_aviator_aviator_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_aviator_aviator_proto_goTypes = []any{
	(*GetCurrentRoundRequest)(nil),  // 0: aviator.GetCurrentRoundRequest
	(*StartRoundRequest)(nil),       // 1: aviator.StartRoundRequest
	(*StreamRoundRequest)(nil),      // 2: aviator.StreamRoundRequest
	(*GetRoundByIdRequest)(nil),     // 3: aviator.GetRoundByIdRequest
	(*GetRoundHistoryRequest)(nil),  // 4: aviator.GetRoundHistoryRequest
	(*GetBetsByRoundRequest)(nil),   // 5: aviator.GetBetsByRoundRequest
	(*GetMyActiveBetsRequest)(nil),  // 6: aviator.GetMyActiveBetsRequest
	(*GetPlayerStatsRequest)(nil),   // 7: aviator.GetPlayerStatsRequest
	(*PlaceBetRequest)(nil),         // 8: aviator.PlaceBetRequest
	(*CancelBetRequest)(nil),        // 9: aviator.CancelBetRequest
	(*CashOutRequest)(nil),          // 10: aviator.CashOutRequest
	(*SetAutoCashOutRequest)(nil),   // 11: aviator.SetAutoCashOutRequest
	(*ClearAutoCashOutRequest)(nil), // 12: aviator.ClearAutoCashOutRequest
	(*RoundResponse)(nil),           // 13: aviator.RoundResponse
	(*RoundTick)(nil),               // 14: aviator.RoundTick
	(*BetResponse)(nil),             // 15: aviator.BetResponse
	(*CashOutResponse)(nil),         // 16: aviator.CashOutResponse
	(*AutoCashOutResponse)(nil),     // 17: aviator.AutoCashOutResponse
	(*BetEntry)(nil),                // 18: aviator.BetEntry
	(*BetsListResponse)(nil),        // 19: aviator.BetsListResponse
	(*RoundHistoryResponse)(nil),    // 20: aviator.RoundHistoryResponse
	(*PlayerStatsResponse)(nil),     // 21: aviator.PlayerStatsResponse
}
var file_aviator_aviator_proto_depIdxs = []int32{
	18, // 0: aviator.BetsListResponse.bets:type_name -> aviator.BetEntry
	13, // 1: aviator.RoundHistoryResponse.rounds:type_name -> aviator.RoundResponse
	0,  // 2: aviator.AviatorService.GetCurrentRound:input_type -> aviator.GetCurrentRoundRequest
	8,  // 3: aviator.AviatorService.PlaceBet:input_type -> aviator.PlaceBetRequest
	9,  // 4: aviator.AviatorService.CancelBet:input_type -> aviator.CancelBetRequest
	10, // 5: aviator.AviatorService.CashOut:input_type -> aviator.CashOutRequest
	11, // 6: aviator.AviatorService.SetAutoCashOut:input_type -> aviator.SetAutoCashOutRequest
	12, // 7: aviator.AviatorService.ClearAutoCashOut:input_type -> aviator.ClearAutoCashOutRequest
	6,  // 8: aviator.AviatorService.GetMyActiveBets:input_type -> aviator.GetMyActiveBetsRequest
	4,  // 9: aviator.AviatorService.GetRoundHistory:input_type -> aviator.GetRoundHistoryRequest
	3,  // 10: aviator.AviatorService.GetRoundById:input_type -> aviator.GetRoundByIdRequest
	5,  // 11: aviator.AviatorService.GetBetsByRound:input_type -> aviator.GetBetsByRoundRequest
	7,  // 12: aviator.AviatorService.GetPlayerStats:input_type -> aviator.GetPlayerStatsRequest
	1,  // 13: aviator.AviatorService.StartRound:input_type -> aviator.StartRoundRequest
	2,  // 14: aviator.AviatorService.StreamRoundUpdates:input_type -> aviator.StreamRoundRequest
	13, // 15: aviator.AviatorService.GetCurrentRound:output_type -> aviator.RoundResponse
	15, // 16: aviator.AviatorService.PlaceBet:output_type -> aviator.BetResponse
	15, // 17: aviator.AviatorService.CancelBet:output_type -> aviator.BetResponse
	16, // 18: aviator.AviatorService.CashOut:output_type -> aviator.CashOutResponse
	17, // 19: aviator.AviatorService.SetAutoCashOut:output_type -> aviator.AutoCashOutResponse
	17, // 20: aviator.AviatorService.ClearAutoCashOut:output_type -> aviator.AutoCashOutResponse
	19, // 21: aviator.AviatorService.GetMyActiveBets:output_type -> aviator.BetsListResponse
	20, // 22: aviator.AviatorService.GetRoundHistory:output_type -> aviator.RoundHistoryResponse
	13, // 23: aviator.AviatorService.GetRoundById:output_type -> aviator.RoundResponse
	19, // 24: aviator.AviatorService.GetBetsByRound:output_type -> aviator.BetsListResponse
	21, // 25: aviator.AviatorService.GetPlayerStats:output_type -> aviator.PlayerStatsResponse
	13, // 26: aviator.AviatorService.StartRound:output_type -> aviator.RoundResponse
	14, // 27: aviator.AviatorService.StreamRoundUpdates:output_type -> aviator.RoundTick
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_aviator_aviator_proto_init() }
func file_aviator_aviator_proto_init() {
	if File_aviator_aviator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aviator_aviator_proto_rawDesc), len(file_aviator_aviator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aviator_aviator_proto_goTypes,
		DependencyIndexes: file_aviator_aviator_proto_depIdxs,
		MessageInfos:      file_aviator_aviator_proto_msgTypes,
	}.Build()
	File_aviator_aviator_proto = out.File
	file_aviator_aviator_proto_goTypes = nil
	file_aviator_aviator_proto_depIdxs = nil
}
