// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: aviator/aviator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AviatorService_GetCurrentRound_FullMethodName    = "/aviator.AviatorService/GetCurrentRound"
	AviatorService_PlaceBet_FullMethodName           = "/aviator.AviatorService/PlaceBet"
	AviatorService_CancelBet_FullMethodName          = "/aviator.AviatorService/CancelBet"
	AviatorService_CashOut_FullMethodName            = "/aviator.AviatorService/CashOut"
	AviatorService_SetAutoCashOut_FullMethodName     = "/aviator.AviatorService/SetAutoCashOut"
	AviatorService_ClearAutoCashOut_FullMethodName   = "/aviator.AviatorService/ClearAutoCashOut"
	AviatorService_GetMyActiveBets_FullMethodName    = "/aviator.AviatorService/GetMyActiveBets"
	AviatorService_GetRoundHistory_FullMethodName    = "/aviator.AviatorService/GetRoundHistory"
	AviatorService_GetRoundById_FullMethodName       = "/aviator.AviatorService/GetRoundById"
	AviatorService_GetBetsByRound_FullMethodName     = "/aviator.AviatorService/GetBetsByRound"
	AviatorService_GetPlayerStats_FullMethodName     = "/aviator.AviatorService/GetPlayerStats"
	AviatorService_StartRound_FullMethodName         = "/aviator.AviatorService/StartRound"
	AviatorService_StreamRoundUpdates_FullMethodName = "/aviator.AviatorService/StreamRoundUpdates"
)

// AviatorServiceClient is the client API for AviatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AviatorServiceClient interface {
	GetCurrentRound(ctx context.Context, in *GetCurrentRoundRequest, opts ...grpc.CallOption) (*RoundResponse, error)
	PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	CancelBet(ctx context.Context, in *CancelBetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	CashOut(ctx context.Context, in *CashOutRequest, opts ...grpc.CallOption) (*CashOutResponse, error)
	SetAutoCashOut(ctx context.Context, in *SetAutoCashOutRequest, opts ...grpc.CallOption) (*AutoCashOutResponse, error)
	ClearAutoCashOut(ctx context.Context, in *ClearAutoCashOutRequest, opts ...grpc.CallOption) (*AutoCashOutResponse, error)
	GetMyActiveBets(ctx context.Context, in *GetMyActiveBetsRequest, opts ...grpc.CallOption) (*BetsListResponse, error)
	GetRoundHistory(ctx context.Context, in *GetRoundHistoryRequest, opts ...grpc.CallOption) (*RoundHistoryResponse, error)
	GetRoundById(ctx context.Context, in *GetRoundByIdRequest, opts ...grpc.CallOption) (*RoundResponse, error)
	GetBetsByRound(ctx context.Context, in *GetBetsByRoundRequest, opts ...grpc.CallOption) (*BetsListResponse, error)
	GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error)
	StartRound(ctx context.Context, in *StartRoundRequest, opts ...grpc.CallOption) (*RoundResponse, error)
	StreamRoundUpdates(ctx context.Context, in *StreamRoundRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoundTick], error)
}

type aviatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAviatorServiceClient(cc grpc.ClientConnInterface) AviatorServiceClient {
	return &aviatorServiceClient{cc}
}

func (c *aviatorServiceClient) GetCurrentRound(ctx context.Context, in *GetCurrentRoundRequest, opts ...grpc.CallOption) (*RoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetCurrentRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, AviatorService_PlaceBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) CancelBet(ctx context.Context, in *CancelBetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, AviatorService_CancelBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) CashOut(ctx context.Context, in *CashOutRequest, opts ...grpc.CallOption) (*CashOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashOutResponse)
	err := c.cc.Invoke(ctx, AviatorService_CashOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) SetAutoCashOut(ctx context.Context, in *SetAutoCashOutRequest, opts ...grpc.CallOption) (*AutoCashOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoCashOutResponse)
	err := c.cc.Invoke(ctx, AviatorService_SetAutoCashOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) ClearAutoCashOut(ctx context.Context, in *ClearAutoCashOutRequest, opts ...grpc.CallOption) (*AutoCashOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoCashOutResponse)
	err := c.cc.Invoke(ctx, AviatorService_ClearAutoCashOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) GetMyActiveBets(ctx context.Context, in *GetMyActiveBetsRequest, opts ...grpc.CallOption) (*BetsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetsListResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetMyActiveBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) GetRoundHistory(ctx context.Context, in *GetRoundHistoryRequest, opts ...grpc.CallOption) (*RoundHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundHistoryResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetRoundHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) GetRoundById(ctx context.Context, in *GetRoundByIdRequest, opts ...grpc.CallOption) (*RoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetRoundById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) GetBetsByRound(ctx context.Context, in *GetBetsByRoundRequest, opts ...grpc.CallOption) (*BetsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetsListResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetBetsByRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatsResponse)
	err := c.cc.Invoke(ctx, AviatorService_GetPlayerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) StartRound(ctx context.Context, in *StartRoundRequest, opts ...grpc.CallOption) (*RoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundResponse)
	err := c.cc.Invoke(ctx, AviatorService_StartRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviatorServiceClient) StreamRoundUpdates(ctx context.Context, in *StreamRoundRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoundTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AviatorService_ServiceDesc.Streams[0], AviatorService_StreamRoundUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRoundRequest, RoundTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AviatorService_StreamRoundUpdatesClient = grpc.ServerStreamingClient[RoundTick]

// AviatorServiceServer is the server API for AviatorService service.
// All implementations must embed UnimplementedAviatorServiceServer
// for forward compatibility.
type AviatorServiceServer interface {
	GetCurrentRound(context.Context, *GetCurrentRoundRequest) (*RoundResponse, error)
	PlaceBet(context.Context, *PlaceBetRequest) (*BetResponse, error)
	CancelBet(context.Context, *CancelBetRequest) (*BetResponse, error)
	CashOut(context.Context, *CashOutRequest) (*CashOutResponse, error)
	SetAutoCashOut(context.Context, *SetAutoCashOutRequest) (*AutoCashOutResponse, error)
	ClearAutoCashOut(context.Context, *ClearAutoCashOutRequest) (*AutoCashOutResponse, error)
	GetMyActiveBets(context.Context, *GetMyActiveBetsRequest) (*BetsListResponse, error)
	GetRoundHistory(context.Context, *GetRoundHistoryRequest) (*RoundHistoryResponse, error)
	GetRoundById(context.Context, *GetRoundByIdRequest) (*RoundResponse, error)
	GetBetsByRound(context.Context, *GetBetsByRoundRequest) (*BetsListResponse, error)
	GetPlayerStats(context.Context, *GetPlayerStatsRequest) (*PlayerStatsResponse, error)
	StartRound(context.Context, *StartRoundRequest) (*RoundResponse, error)
	StreamRoundUpdates(*StreamRoundRequest, grpc.ServerStreamingServer[RoundTick]) error
	mustEmbedUnimplementedAviatorServiceServer()
}

// UnimplementedAviatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAviatorServiceServer struct{}

func (UnimplementedAviatorServiceServer) GetCurrentRound(context.Context, *GetCurrentRoundRequest) (*RoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentRound not implemented")
}
func (UnimplementedAviatorServiceServer) PlaceBet(context.Context, *PlaceBetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedAviatorServiceServer) CancelBet(context.Context, *CancelBetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBet not implemented")
}
func (UnimplementedAviatorServiceServer) CashOut(context.Context, *CashOutRequest) (*CashOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashOut not implemented")
}
func (UnimplementedAviatorServiceServer) SetAutoCashOut(context.Context, *SetAutoCashOutRequest) (*AutoCashOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutoCashOut not implemented")
}
func (UnimplementedAviatorServiceServer) ClearAutoCashOut(context.Context, *ClearAutoCashOutRequest) (*AutoCashOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearAutoCashOut not implemented")
}
func (UnimplementedAviatorServiceServer) GetMyActiveBets(context.Context, *GetMyActiveBetsRequest) (*BetsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyActiveBets not implemented")
}
func (UnimplementedAviatorServiceServer) GetRoundHistory(context.Context, *GetRoundHistoryRequest) (*RoundHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoundHistory not implemented")
}
func (UnimplementedAviatorServiceServer) GetRoundById(context.Context, *GetRoundByIdRequest) (*RoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoundById not implemented")
}
func (UnimplementedAviatorServiceServer) GetBetsByRound(context.Context, *GetBetsByRoundRequest) (*BetsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBetsByRound not implemented")
}
func (UnimplementedAviatorServiceServer) GetPlayerStats(context.Context, *GetPlayerStatsRequest) (*PlayerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerStats not implemented")
}
func (UnimplementedAviatorServiceServer) StartRound(context.Context, *StartRoundRequest) (*RoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRound not implemented")
}
func (UnimplementedAviatorServiceServer) StreamRoundUpdates(*StreamRoundRequest, grpc.ServerStreamingServer[RoundTick]) error {
	return status.Error(codes.Unimplemented, "method StreamRoundUpdates not implemented")
}
func (UnimplementedAviatorServiceServer) mustEmbedUnimplementedAviatorServiceServer() {}
func (UnimplementedAviatorServiceServer) testEmbeddedByValue()                        {}

// UnsafeAviatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AviatorServiceServer will
// result in compilation errors.
type UnsafeAviatorServiceServer interface {
	mustEmbedUnimplementedAviatorServiceServer()
}

func RegisterAviatorServiceServer(s grpc.ServiceRegistrar, srv AviatorServiceServer) {
	// If the following call panics, it indicates UnimplementedAviatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AviatorService_ServiceDesc, srv)
}

func _AviatorService_GetCurrentRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetCurrentRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetCurrentRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetCurrentRound(ctx, req.(*GetCurrentRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_PlaceBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).PlaceBet(ctx, req.(*PlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_CancelBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).CancelBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_CancelBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).CancelBet(ctx, req.(*CancelBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_CashOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).CashOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_CashOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).CashOut(ctx, req.(*CashOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_SetAutoCashOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoCashOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).SetAutoCashOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_SetAutoCashOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).SetAutoCashOut(ctx, req.(*SetAutoCashOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_ClearAutoCashOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAutoCashOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).ClearAutoCashOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_ClearAutoCashOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).ClearAutoCashOut(ctx, req.(*ClearAutoCashOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_GetMyActiveBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyActiveBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetMyActiveBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetMyActiveBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetMyActiveBets(ctx, req.(*GetMyActiveBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_GetRoundHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetRoundHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetRoundHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetRoundHistory(ctx, req.(*GetRoundHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_GetRoundById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetRoundById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetRoundById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetRoundById(ctx, req.(*GetRoundByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_GetBetsByRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBetsByRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetBetsByRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetBetsByRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetBetsByRound(ctx, req.(*GetBetsByRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_GetPlayerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).GetPlayerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_GetPlayerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).GetPlayerStats(ctx, req.(*GetPlayerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_StartRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatorServiceServer).StartRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatorService_StartRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatorServiceServer).StartRound(ctx, req.(*StartRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviatorService_StreamRoundUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRoundRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AviatorServiceServer).StreamRoundUpdates(m, &grpc.GenericServerStream[StreamRoundRequest, RoundTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AviatorService_StreamRoundUpdatesServer = grpc.ServerStreamingServer[RoundTick]

// AviatorService_ServiceDesc is the grpc.ServiceDesc for AviatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AviatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviator.AviatorService",
	HandlerType: (*AviatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentRound",
			Handler:    _AviatorService_GetCurrentRound_Handler,
		},
		{
			MethodName: "PlaceBet",
			Handler:    _AviatorService_PlaceBet_Handler,
		},
		{
			MethodName: "CancelBet",
			Handler:    _AviatorService_CancelBet_Handler,
		},
		{
			MethodName: "CashOut",
			Handler:    _AviatorService_CashOut_Handler,
		},
		{
			MethodName: "SetAutoCashOut",
			Handler:    _AviatorService_SetAutoCashOut_Handler,
		},
		{
			MethodName: "ClearAutoCashOut",
			Handler:    _AviatorService_ClearAutoCashOut_Handler,
		},
		{
			MethodName: "GetMyActiveBets",
			Handler:    _AviatorService_GetMyActiveBets_Handler,
		},
		{
			MethodName: "GetRoundHistory",
			Handler:    _AviatorService_GetRoundHistory_Handler,
		},
		{
			MethodName: "GetRoundById",
			Handler:    _AviatorService_GetRoundById_Handler,
		},
		{
			MethodName: "GetBetsByRound",
			Handler:    _AviatorService_GetBetsByRound_Handler,
		},
		{
			MethodName: "GetPlayerStats",
			Handler:    _AviatorService_GetPlayerStats_Handler,
		},
		{
			MethodName: "StartRound",
			Handler:    _AviatorService_StartRound_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRoundUpdates",
			Handler:       _AviatorService_StreamRoundUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aviator/aviator.proto",
}
