// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: balloon/balloon.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalloonService_StartSession_FullMethodName     = "/balloon.BalloonService/StartSession"
	BalloonService_PlaceBet_FullMethodName         = "/balloon.BalloonService/PlaceBet"
	BalloonService_Pump_FullMethodName             = "/balloon.BalloonService/Pump"
	BalloonService_Release_FullMethodName          = "/balloon.BalloonService/Release"
	BalloonService_GetActiveSession_FullMethodName = "/balloon.BalloonService/GetActiveSession"
	BalloonService_AbortSession_FullMethodName     = "/balloon.BalloonService/AbortSession"
	BalloonService_GetSessionResult_FullMethodName = "/balloon.BalloonService/GetSessionResult"
	BalloonService_GetHistory_FullMethodName       = "/balloon.BalloonService/GetHistory"
	BalloonService_GetConfig_FullMethodName        = "/balloon.BalloonService/GetConfig"
	BalloonService_ValidatePumpRate_FullMethodName = "/balloon.BalloonService/ValidatePumpRate"
	BalloonService_GetPlayerStats_FullMethodName   = "/balloon.BalloonService/GetPlayerStats"
	BalloonService_StreamPumpTicks_FullMethodName  = "/balloon.BalloonService/StreamPumpTicks"
)

// BalloonServiceClient is the client API for BalloonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalloonServiceClient interface {
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	Pump(ctx context.Context, in *PumpRequest, opts ...grpc.CallOption) (*PumpResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	GetActiveSession(ctx context.Context, in *GetActiveSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	AbortSession(ctx context.Context, in *AbortSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	GetSessionResult(ctx context.Context, in *GetSessionResultRequest, opts ...grpc.CallOption) (*SessionResultResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	ValidatePumpRate(ctx context.Context, in *ValidatePumpRateRequest, opts ...grpc.CallOption) (*ValidatePumpRateResponse, error)
	GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error)
	StreamPumpTicks(ctx context.Context, in *StreamPumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PumpTick], error)
}

type balloonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalloonServiceClient(cc grpc.ClientConnInterface) BalloonServiceClient {
	return &balloonServiceClient{cc}
}

func (c *balloonServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, BalloonService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, BalloonService_PlaceBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) Pump(ctx context.Context, in *PumpRequest, opts ...grpc.CallOption) (*PumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PumpResponse)
	err := c.cc.Invoke(ctx, BalloonService_Pump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, BalloonService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) GetActiveSession(ctx context.Context, in *GetActiveSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, BalloonService_GetActiveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) AbortSession(ctx context.Context, in *AbortSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, BalloonService_AbortSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) GetSessionResult(ctx context.Context, in *GetSessionResultRequest, opts ...grpc.CallOption) (*SessionResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResultResponse)
	err := c.cc.Invoke(ctx, BalloonService_GetSessionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, BalloonService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, BalloonService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) ValidatePumpRate(ctx context.Context, in *ValidatePumpRateRequest, opts ...grpc.CallOption) (*ValidatePumpRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePumpRateResponse)
	err := c.cc.Invoke(ctx, BalloonService_ValidatePumpRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*PlayerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatsResponse)
	err := c.cc.Invoke(ctx, BalloonService_GetPlayerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balloonServiceClient) StreamPumpTicks(ctx context.Context, in *StreamPumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PumpTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BalloonService_ServiceDesc.Streams[0], BalloonService_StreamPumpTicks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPumpRequest, PumpTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BalloonService_StreamPumpTicksClient = grpc.ServerStreamingClient[PumpTick]

// BalloonServiceServer is the server API for BalloonService service.
// All implementations must embed UnimplementedBalloonServiceServer
// for forward compatibility.
type BalloonServiceServer interface {
	StartSession(context.Context, *StartSessionRequest) (*SessionResponse, error)
	PlaceBet(context.Context, *PlaceBetRequest) (*BetResponse, error)
	Pump(context.Context, *PumpRequest) (*PumpResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	GetActiveSession(context.Context, *GetActiveSessionRequest) (*SessionResponse, error)
	AbortSession(context.Context, *AbortSessionRequest) (*SessionResponse, error)
	GetSessionResult(context.Context, *GetSessionResultRequest) (*SessionResultResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error)
	ValidatePumpRate(context.Context, *ValidatePumpRateRequest) (*ValidatePumpRateResponse, error)
	GetPlayerStats(context.Context, *GetPlayerStatsRequest) (*PlayerStatsResponse, error)
	StreamPumpTicks(*StreamPumpRequest, grpc.ServerStreamingServer[PumpTick]) error
	mustEmbedUnimplementedBalloonServiceServer()
}

// UnimplementedBalloonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalloonServiceServer struct{}

func (UnimplementedBalloonServiceServer) StartSession(context.Context, *StartSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedBalloonServiceServer) PlaceBet(context.Context, *PlaceBetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedBalloonServiceServer) Pump(context.Context, *PumpRequest) (*PumpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pump not implemented")
}
func (UnimplementedBalloonServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedBalloonServiceServer) GetActiveSession(context.Context, *GetActiveSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveSession not implemented")
}
func (UnimplementedBalloonServiceServer) AbortSession(context.Context, *AbortSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortSession not implemented")
}
func (UnimplementedBalloonServiceServer) GetSessionResult(context.Context, *GetSessionResultRequest) (*SessionResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionResult not implemented")
}
func (UnimplementedBalloonServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedBalloonServiceServer) GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedBalloonServiceServer) ValidatePumpRate(context.Context, *ValidatePumpRateRequest) (*ValidatePumpRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePumpRate not implemented")
}
func (UnimplementedBalloonServiceServer) GetPlayerStats(context.Context, *GetPlayerStatsRequest) (*PlayerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerStats not implemented")
}
func (UnimplementedBalloonServiceServer) StreamPumpTicks(*StreamPumpRequest, grpc.ServerStreamingServer[PumpTick]) error {
	return status.Error(codes.Unimplemented, "method StreamPumpTicks not implemented")
}
func (UnimplementedBalloonServiceServer) mustEmbedUnimplementedBalloonServiceServer() {}
func (UnimplementedBalloonServiceServer) testEmbeddedByValue()                        {}

// UnsafeBalloonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalloonServiceServer will
// result in compilation errors.
type UnsafeBalloonServiceServer interface {
	mustEmbedUnimplementedBalloonServiceServer()
}

func RegisterBalloonServiceServer(s grpc.ServiceRegistrar, srv BalloonServiceServer) {
	// If the following call panics, it indicates UnimplementedBalloonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalloonService_ServiceDesc, srv)
}

func _BalloonService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_PlaceBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).PlaceBet(ctx, req.(*PlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_Pump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).Pump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_Pump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).Pump(ctx, req.(*PumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_GetActiveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).GetActiveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_GetActiveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).GetActiveSession(ctx, req.(*GetActiveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_AbortSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).AbortSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_AbortSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).AbortSession(ctx, req.(*AbortSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_GetSessionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).GetSessionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_GetSessionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).GetSessionResult(ctx, req.(*GetSessionResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_ValidatePumpRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePumpRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).ValidatePumpRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_ValidatePumpRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).ValidatePumpRate(ctx, req.(*ValidatePumpRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_GetPlayerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalloonServiceServer).GetPlayerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalloonService_GetPlayerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalloonServiceServer).GetPlayerStats(ctx, req.(*GetPlayerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalloonService_StreamPumpTicks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BalloonServiceServer).StreamPumpTicks(m, &grpc.GenericServerStream[StreamPumpRequest, PumpTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BalloonService_StreamPumpTicksServer = grpc.ServerStreamingServer[PumpTick]

// BalloonService_ServiceDesc is the grpc.ServiceDesc for BalloonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalloonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balloon.BalloonService",
	HandlerType: (*BalloonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _BalloonService_StartSession_Handler,
		},
		{
			MethodName: "PlaceBet",
			Handler:    _BalloonService_PlaceBet_Handler,
		},
		{
			MethodName: "Pump",
			Handler:    _BalloonService_Pump_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _BalloonService_Release_Handler,
		},
		{
			MethodName: "GetActiveSession",
			Handler:    _BalloonService_GetActiveSession_Handler,
		},
		{
			MethodName: "AbortSession",
			Handler:    _BalloonService_AbortSession_Handler,
		},
		{
			MethodName: "GetSessionResult",
			Handler:    _BalloonService_GetSessionResult_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _BalloonService_GetHistory_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _BalloonService_GetConfig_Handler,
		},
		{
			MethodName: "ValidatePumpRate",
			Handler:    _BalloonService_ValidatePumpRate_Handler,
		},
		{
			MethodName: "GetPlayerStats",
			Handler:    _BalloonService_GetPlayerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPumpTicks",
			Handler:       _BalloonService_StreamPumpTicks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "balloon/balloon.proto",
}
