// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: balloon/balloon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetActiveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSessionRequest) Reset() {
	*x = GetActiveSessionRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSessionRequest) ProtoMessage() {}

func (x *GetActiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSessionRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{1}
}

func (x *GetActiveSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{2}
}

func (x *AbortSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSessionResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResultRequest) Reset() {
	*x = GetSessionResultRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResultRequest) ProtoMessage() {}

func (x *GetSessionResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResultRequest.ProtoReflect.Descriptor instead.
func (*GetSessionResultRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{5}
}

type StreamPumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPumpRequest) Reset() {
	*x = StreamPumpRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPumpRequest) ProtoMessage() {}

func (x *StreamPumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPumpRequest.ProtoReflect.Descriptor instead.
func (*StreamPumpRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{6}
}

func (x *StreamPumpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPlayerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatsRequest) Reset() {
	*x = GetPlayerStatsRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsRequest) ProtoMessage() {}

func (x *GetPlayerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayerStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PlaceBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{8}
}

func (x *PlaceBetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceBetRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type PumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PumpRequest) Reset() {
	*x = PumpRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PumpRequest) ProtoMessage() {}

func (x *PumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PumpRequest.ProtoReflect.Descriptor instead.
func (*PumpRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{9}
}

func (x *PumpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidatePumpRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePumpRateRequest) Reset() {
	*x = ValidatePumpRateRequest{}
	mi := &file_balloon_balloon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePumpRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePumpRateRequest) ProtoMessage() {}

func (x *ValidatePumpRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePumpRateRequest.ProtoReflect.Descriptor instead.
func (*ValidatePumpRateRequest) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{11}
}

func (x *ValidatePumpRateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidatePumpRateRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type SessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,3,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	BetAmountCents    int64                  `protobuf:"varint,4,opt,name=bet_amount_cents,json=betAmountCents,proto3" json:"bet_amount_cents,omitempty"`
	StartedAt         int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{12}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResponse) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *SessionResponse) GetBetAmountCents() int64 {
	if x != nil {
		return x.BetAmountCents
	}
	return 0
}

func (x *SessionResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type PumpResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,2,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	Popped            bool                   `protobuf:"varint,3,opt,name=popped,proto3" json:"popped,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PumpResponse) Reset() {
	*x = PumpResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PumpResponse) ProtoMessage() {}

func (x *PumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PumpResponse.ProtoReflect.Descriptor instead.
func (*PumpResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{13}
}

func (x *PumpResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PumpResponse) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *PumpResponse) GetPopped() bool {
	if x != nil {
		return x.Popped
	}
	return false
}

func (x *PumpResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PumpTick struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,2,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	Popped            bool                   `protobuf:"varint,3,opt,name=popped,proto3" json:"popped,omitempty"`
	ServerTime        int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PumpTick) Reset() {
	*x = PumpTick{}
	mi := &file_balloon_balloon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PumpTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PumpTick) ProtoMessage() {}

func (x *PumpTick) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PumpTick.ProtoReflect.Descriptor instead.
func (*PumpTick) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{14}
}

func (x *PumpTick) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PumpTick) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *PumpTick) GetPopped() bool {
	if x != nil {
		return x.Popped
	}
	return false
}

func (x *PumpTick) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type BetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,4,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetResponse) Reset() {
	*x = BetResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResponse) ProtoMessage() {}

func (x *BetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResponse.ProtoReflect.Descriptor instead.
func (*BetResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{15}
}

func (x *BetResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BetResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BetResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BetResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

func (x *BetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	PayoutCents   int64                  `protobuf:"varint,3,opt,name=payout_cents,json=payoutCents,proto3" json:"payout_cents,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,4,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	Popped        bool                   `protobuf:"varint,5,opt,name=popped,proto3" json:"popped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReleaseResponse) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *ReleaseResponse) GetPayoutCents() int64 {
	if x != nil {
		return x.PayoutCents
	}
	return 0
}

func (x *ReleaseResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

func (x *ReleaseResponse) GetPopped() bool {
	if x != nil {
		return x.Popped
	}
	return false
}

type SessionResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	PayoutCents   int64                  `protobuf:"varint,4,opt,name=payout_cents,json=payoutCents,proto3" json:"payout_cents,omitempty"`
	Won           bool                   `protobuf:"varint,5,opt,name=won,proto3" json:"won,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResultResponse) Reset() {
	*x = SessionResultResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResultResponse) ProtoMessage() {}

func (x *SessionResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResultResponse.ProtoReflect.Descriptor instead.
func (*SessionResultResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{17}
}

func (x *SessionResultResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResultResponse) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *SessionResultResponse) GetPayoutCents() int64 {
	if x != nil {
		return x.PayoutCents
	}
	return 0
}

func (x *SessionResultResponse) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

type HistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	PayoutCents   int64                  `protobuf:"varint,4,opt,name=payout_cents,json=payoutCents,proto3" json:"payout_cents,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_balloon_balloon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{18}
}

func (x *HistoryEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HistoryEntry) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *HistoryEntry) GetPayoutCents() int64 {
	if x != nil {
		return x.PayoutCents
	}
	return 0
}

func (x *HistoryEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*HistoryEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{19}
}

func (x *HistoryResponse) GetEntries() []*HistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinBetCents   int64                  `protobuf:"varint,1,opt,name=min_bet_cents,json=minBetCents,proto3" json:"min_bet_cents,omitempty"`
	MaxBetCents   int64                  `protobuf:"varint,2,opt,name=max_bet_cents,json=maxBetCents,proto3" json:"max_bet_cents,omitempty"`
	PumpRate      float64                `protobuf:"fixed64,3,opt,name=pump_rate,json=pumpRate,proto3" json:"pump_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigResponse) GetMinBetCents() int64 {
	if x != nil {
		return x.MinBetCents
	}
	return 0
}

func (x *ConfigResponse) GetMaxBetCents() int64 {
	if x != nil {
		return x.MaxBetCents
	}
	return 0
}

func (x *ConfigResponse) GetPumpRate() float64 {
	if x != nil {
		return x.PumpRate
	}
	return 0
}

type ValidatePumpRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePumpRateResponse) Reset() {
	*x = ValidatePumpRateResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePumpRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePumpRateResponse) ProtoMessage() {}

func (x *ValidatePumpRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePumpRateResponse.ProtoReflect.Descriptor instead.
func (*ValidatePumpRateResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{21}
}

func (x *ValidatePumpRateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidatePumpRateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSessions     int32                  `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	TotalWins         int32                  `protobuf:"varint,2,opt,name=total_wins,json=totalWins,proto3" json:"total_wins,omitempty"`
	TotalWageredCents int64                  `protobuf:"varint,3,opt,name=total_wagered_cents,json=totalWageredCents,proto3" json:"total_wagered_cents,omitempty"`
	TotalWonCents     int64                  `protobuf:"varint,4,opt,name=total_won_cents,json=totalWonCents,proto3" json:"total_won_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerStatsResponse) Reset() {
	*x = PlayerStatsResponse{}
	mi := &file_balloon_balloon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsResponse) ProtoMessage() {}

func (x *PlayerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balloon_balloon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsResponse.ProtoReflect.Descriptor instead.
func (*PlayerStatsResponse) Descriptor() ([]byte, []int) {
	return file_balloon_balloon_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerStatsResponse) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWins() int32 {
	if x != nil {
		return x.TotalWins
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWageredCents() int64 {
	if x != nil {
		return x.TotalWageredCents
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWonCents() int64 {
	if x != nil {
		return x.TotalWonCents
	}
	return 0
}

var File_balloon_balloon_proto protoreflect.FileDescriptor

const file_balloon_balloon_proto_rawDesc = "" +
	"\n" +
	"\x15balloon/balloon.proto\x12\aballoon\".\n" +
	"\x13StartSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x17GetActiveSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x13AbortSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x17GetSessionResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"B\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x12\n" +
	"\x10GetConfigRequest\",\n" +
	"\x11StreamPumpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x15GetPlayerStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x0fPlaceBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\"&\n" +
	"\vPumpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\")\n" +
	"\x0eReleaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x17ValidatePumpRateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\xc0\x01\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12current_multiplier\x18\x03 \x01(\x01R\x11currentMultiplier\x12(\n" +
	"\x10bet_amount_cents\x18\x04 \x01(\x03R\x0ebetAmountCents\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\"\x8c\x01\n" +
	"\fPumpResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x12current_multiplier\x18\x02 \x01(\x01R\x11currentMultiplier\x12\x16\n" +
	"\x06popped\x18\x03 \x01(\bR\x06popped\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x91\x01\n" +
	"\bPumpTick\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x12current_multiplier\x18\x02 \x01(\x01R\x11currentMultiplier\x12\x16\n" +
	"\x06popped\x18\x03 \x01(\bR\x06popped\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"\xa5\x01\n" +
	"\vBetResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12#\n" +
	"\rbalance_cents\x18\x04 \x01(\x03R\fbalanceCents\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xb0\x01\n" +
	"\x0fReleaseResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x01R\n" +
	"multiplier\x12!\n" +
	"\fpayout_cents\x18\x03 \x01(\x03R\vpayoutCents\x12#\n" +
	"\rbalance_cents\x18\x04 \x01(\x03R\fbalanceCents\x12\x16\n" +
	"\x06popped\x18\x05 \x01(\bR\x06popped\"\xa3\x01\n" +
	"\x15SessionResultResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\x12!\n" +
	"\fpayout_cents\x18\x04 \x01(\x03R\vpayoutCents\x12\x10\n" +
	"\x03won\x18\x05 \x01(\bR\x03won\"\xa7\x01\n" +
	"\fHistoryEntry\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\x12!\n" +
	"\fpayout_cents\x18\x04 \x01(\x03R\vpayoutCents\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"B\n" +
	"\x0fHistoryResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.balloon.HistoryEntryR\aentries\"u\n" +
	"\x0eConfigResponse\x12\"\n" +
	"\rmin_bet_cents\x18\x01 \x01(\x03R\vminBetCents\x12\"\n" +
	"\rmax_bet_cents\x18\x02 \x01(\x03R\vmaxBetCents\x12\x1b\n" +
	"\tpump_rate\x18\x03 \x01(\x01R\bpumpRate\"L\n" +
	"\x18ValidatePumpRateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xb3\x01\n" +
	"\x13PlayerStatsResponse\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\x05R\rtotalSessions\x12\x1d\n" +
	"\n" +
	"total_wins\x18\x02 \x01(\x05R\ttotalWins\x12.\n" +
	"\x13total_wagered_cents\x18\x03 \x01(\x03R\x11totalWageredCents\x12&\n" +
	"\x0ftotal_won_cents\x18\x04 \x01(\x03R\rtotalWonCents2\xe7\x06\n" +
	"\x0eBalloonService\x12F\n" +
	"\fStartSession\x12\x1c.balloon.StartSessionRequest\x1a\x18.balloon.SessionResponse\x12:\n" +
	"\bPlaceBet\x12\x18.balloon.PlaceBetRequest\x1a\x14.balloon.BetResponse\x123\n" +
	"\x04Pump\x12\x14.balloon.PumpRequest\x1a\x15.balloon.PumpResponse\x12<\n" +
	"\aRelease\x12\x17.balloon.ReleaseRequest\x1a\x18.balloon.ReleaseResponse\x12N\n" +
	"\x10GetActiveSession\x12 .balloon.GetActiveSessionRequest\x1a\x18.balloon.SessionResponse\x12F\n" +
	"\fAbortSession\x12\x1c.balloon.AbortSessionRequest\x1a\x18.balloon.SessionResponse\x12T\n" +
	"\x10GetSessionResult\x12 .balloon.GetSessionResultRequest\x1a\x1e.balloon.SessionResultResponse\x12B\n" +
	"\n" +
	"GetHistory\x12\x1a.balloon.GetHistoryRequest\x1a\x18.balloon.HistoryResponse\x12?\n" +
	"\tGetConfig\x12\x19.balloon.GetConfigRequest\x1a\x17.balloon.ConfigResponse\x12W\n" +
	"\x10ValidatePumpRate\x12 .balloon.ValidatePumpRateRequest\x1a!.balloon.ValidatePumpRateResponse\x12N\n" +
	"\x0eGetPlayerStats\x12\x1e.balloon.GetPlayerStatsRequest\x1a\x1c.balloon.PlayerStatsResponse\x12B\n" +
	"\x0fStreamPumpTicks\x12\x1a.balloon.StreamPumpRequest\x1a\x11.balloon.PumpTick0\x01B3Z1github.com/akadilxbet/balloon-service/internal/pbb\x06proto3"

var (
	file_balloon_balloon_proto_rawDescOnce sync.Once
	file_balloon_balloon_proto_rawDescData []byte
)

func file_balloon_balloon_proto_rawDescGZIP() []byte {
	file_balloon_balloon_proto_rawDescOnce.Do(func() {
		file_balloon_balloon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balloon_balloon_proto_rawDesc), len(file_balloon_balloon_proto_rawDesc)))
	})
	return file_balloon_balloon_proto_rawDescData
}

var file_balloon_balloon_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_balloon_balloon_proto_goTypes = []any{
	(*StartSessionRequest)(nil),      // 0: balloon.StartSessionRequest
	(*GetActiveSessionRequest)(nil),  // 1: balloon.GetActiveSessionRequest
	(*AbortSessionRequest)(nil),      // 2: balloon.AbortSessionRequest
	(*GetSessionResultRequest)(nil),  // 3: balloon.GetSessionResultRequest
	(*GetHistoryRequest)(nil),        // 4: balloon.GetHistoryRequest
	(*GetConfigRequest)(nil),         // 5: balloon.GetConfigRequest
	(*StreamPumpRequest)(nil),        // 6: balloon.StreamPumpRequest
	(*GetPlayerStatsRequest)(nil),    // 7: balloon.GetPlayerStatsRequest
	(*PlaceBetRequest)(nil),          // 8: balloon.PlaceBetRequest
	(*PumpRequest)(nil),              // 9: balloon.PumpRequest
	(*ReleaseRequest)(nil),           // 10: balloon.ReleaseRequest
	(*ValidatePumpRateRequest)(nil),  // 11: balloon.ValidatePumpRateRequest
	(*SessionResponse)(nil),          // 12: balloon.SessionResponse
	(*PumpResponse)(nil),             // 13: balloon.PumpResponse
	(*PumpTick)(nil),                 // 14: balloon.PumpTick
	(*BetResponse)(nil),              // 15: balloon.BetResponse
	(*ReleaseResponse)(nil),          // 16: balloon.ReleaseResponse
	(*SessionResultResponse)(nil),    // 17: balloon.SessionResultResponse
	(*HistoryEntry)(nil),             // 18: balloon.HistoryEntry
	(*HistoryResponse)(nil),          // 19: balloon.HistoryResponse
	(*ConfigResponse)(nil),           // 20: balloon.ConfigResponse
	(*ValidatePumpRateResponse)(nil), // 21: balloon.ValidatePumpRateResponse
	(*PlayerStatsResponse)(nil),      // 22: balloon.PlayerStatsResponse
}
var file_balloon_balloon_proto_depIdxs = []int32{
	18, // 0: balloon.HistoryResponse.entries:type_name -> balloon.HistoryEntry
	0,  // 1: balloon.BalloonService.StartSession:input_type -> balloon.StartSessionRequest
	8,  // 2: balloon.BalloonService.PlaceBet:input_type -> balloon.PlaceBetRequest
	9,  // 3: balloon.BalloonService.Pump:input_type -> balloon.PumpRequest
	10, // 4: balloon.BalloonService.Release:input_type -> balloon.ReleaseRequest
	1,  // 5: balloon.BalloonService.GetActiveSession:input_type -> balloon.GetActiveSessionRequest
	2,  // 6: balloon.BalloonService.AbortSession:input_type -> balloon.AbortSessionRequest
	3,  // 7: balloon.BalloonService.GetSessionResult:input_type -> balloon.GetSessionResultRequest
	4,  // 8: balloon.BalloonService.GetHistory:input_type -> balloon.GetHistoryRequest
	5,  // 9: balloon.BalloonService.GetConfig:input_type -> balloon.GetConfigRequest
	11, // 10: balloon.BalloonService.ValidatePumpRate:input_type -> balloon.ValidatePumpRateRequest
	7,  // 11: balloon.BalloonService.GetPlayerStats:input_type -> balloon.GetPlayerStatsRequest
	6,  // 12: balloon.BalloonService.StreamPumpTicks:input_type -> balloon.StreamPumpRequest
	12, // 13: balloon.BalloonService.StartSession:output_type -> balloon.SessionResponse
	15, // 14: balloon.BalloonService.PlaceBet:output_type -> balloon.BetResponse
	13, // 15: balloon.BalloonService.Pump:output_type -> balloon.PumpResponse
	16, // 16: balloon.BalloonService.Release:output_type -> balloon.ReleaseResponse
	12, // 17: balloon.BalloonService.GetActiveSession:output_type -> balloon.SessionResponse
	12, // 18: balloon.BalloonService.AbortSession:output_type -> balloon.SessionResponse
	17, // 19: balloon.BalloonService.GetSessionResult:output_type -> balloon.SessionResultResponse
	19, // 20: balloon.BalloonService.GetHistory:output_type -> balloon.HistoryResponse
	20, // 21: balloon.BalloonService.GetConfig:output_type -> balloon.ConfigResponse
	21, // 22: balloon.BalloonService.ValidatePumpRate:output_type -> balloon.ValidatePumpRateResponse
	22, // 23: balloon.BalloonService.GetPlayerStats:output_type -> balloon.PlayerStatsResponse
	14, // 24: balloon.BalloonService.StreamPumpTicks:output_type -> balloon.PumpTick
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_balloon_balloon_proto_init() }
func file_balloon_balloon_proto_init() {
	if File_balloon_balloon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balloon_balloon_proto_rawDesc), len(file_balloon_balloon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balloon_balloon_proto_goTypes,
		DependencyIndexes: file_balloon_balloon_proto_depIdxs,
		MessageInfos:      file_balloon_balloon_proto_msgTypes,
	}.Build()
	File_balloon_balloon_proto = out.File
	file_balloon_balloon_proto_goTypes = nil
	file_balloon_balloon_proto_depIdxs = nil
}
